# Copyright 2020 Google LLC

name: "do-not-merge"

on:
  pull_request:
    types:
    - labeled
    - unlabeled
    - opened
    - synchronize
    branches:
    - master

jobs:
  check-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check for "DO NOT MERGE" label
        if: ${{ contains(github.event.pull_request.labels.*.name, 'DO NOT MERGE') }}
        run: exit 1
