# Copyright 2021 Google LLC

name: "npm-dependency-check"

on:
  pull_request:
    branches:
      - master
    paths:
    - "**/package.json"
    - "**/package-lock.json"
    - ".github/workflows/pr-dependency-check.yaml"
jobs:
  package-lock-changes:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.16.2'
    - run: npm install -g npm@6.14.4
    - run: npm install
    - name: check for changes
      run: git diff --exit-code
